name: debug
"on": workflow_dispatch
jobs:
  issue_245:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: debug
      - run: npm ci
      - run: npm run build
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Debug
          body: "debugging #245"
          branch: debug-issue-245
          path: test.txt
          commit-message: debug
          author: amanstep <aman@stepsecurity.io>
          reviewers: amanstep
