name: debug
"on": workflow_dispatch
jobs:
  issue_245:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: debug
      - run: npm ci
      - run: npm run build
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Debug
          body: "debugging #245"
          branch: debug-issue-245
          path: test.txt
          commit-message: debug
          author: amanstep <aman@stepsecurity.io>
          reviewers: amanstep
